close all 
clear all
clc

addpath(genpath('replay-bg'))

load(fullfile('results','workspaces','identification_patient1_tr_5_trIdx_9.mat'));
load(fullfile('results','modelParameters','modelParameters_patient1_tr_5_trIdx_9.mat'));

% %Run replay-bg
replayBG('replay',data,modelParameters.BW,'single-meal','patient1_tr_5_trIdx_9',...
     'cgmModel','CGM',...
     'glucoseModel','IG',...
     'sampleTime',5,...
     'seed',1,...
     'pathology','t1d',...
     'bolusSource','data',...
     'basalSource','data',...
     'choSource','data',...
     'bolusCalculatorHandler','standardBolusCalculatorHandler',...
     'bolusCalculatorHandlerParams',[],...
     'basalHandler','defaultBasalHandler',...
     'basalHandlerParams',[],...
     'mealGeneratorHandler','defaultMealGeneratorHandler',...
     'mealGeneratorHandlerParams',[],...
     'CR',10,...
     'CF',40,...
     'GT',120,...
     'enableHypoTreatments',0,...
     'hypoTreatmentsHandler','adaHypoTreatmentsHandler',...
     'hypoTreatmentsHandlerParams',[],...
     'enableCorrectionBoluses',0,...
     'correctionBolusesHandler','correctsAbove250Handler',...
     'correctionBolusesHandlerParams',[],...
     'saveSuffix','demo',...
     'plotMode',1,...
     'enableLog',1,...
     'verbose',1); 

 %If set, ignored during 'replay'
 %'maxETAPerMCMCRun','maxMCMCIterations', 'maxMCMCRuns', 'maxMCMCRunsWithMaxETA'
 %'adaptiveSCMH','MCMCTheta0Policy','bayesianEstimator',
 %'preFilterData','saveChains'